[package]
name = "chinese2digits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
rust_decimal = "*"
# pcre2 = "*"
# lazy_static = "1.4"
